id: opecha:P006968
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS54156
  title: ལེགས་བཤད་དཔེ་ཚོགས་ནོར་བུའི་ཕྲེང་བ། （༡）
  volume:
    52bdf9951ff6420ba19050717232b8db:
      image_group_id: I1KG13745
      title: Volume 1 of legs bshad dpe tshogs nor bu'i phreng ba :1
      volume_number: 1
      total_pages: 600
  author: ''
ebook_metadata:
  title: ལེགས་བཤད་དཔེ་ཚོགས་ནོར་བུའི་ཕྲེང་བ། （༡）
  author: ''
  sku: P006968
  cover: cover.jpg
  layers:
  - pagination
