id: P006968
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS54156
  title: ལེགས་བཤད་དཔེ་ཚོགས་ནོར་བུའི་ཕྲེང་བ། （༡）
  author: ''
  volumes:
    1abfe63d960e402fb62d20b216cd31a8:
      image_group_id: I1KG13745
      title: ''
      volume_number: 1
      total_pages: 600
ebook_metadata:
  title: ལེགས་བཤད་དཔེ་ཚོགས་ནོར་བུའི་ཕྲེང་བ། （༡）
  author: ''
  sku: P006968
  cover: cover.jpg
  layers:
  - pagination
