id: P006968
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1GS54156
  title: ལེགས་བཤད་དཔེ་ཚོགས་ནོར་བུའི་ཕྲེང་བ། （༡）
  author: ''
  volumes:
    52bdf9951ff6420ba19050717232b8db:
      image_group_id: I1KG13745
      title: Volume 1 of legs bshad dpe tshogs nor bu'i phreng ba :1
      volume_number: 1
      total_pages: 600
      base_file: v001.txt
