id: I1980B469
legacy_id: P006968
ocr_import_info:
  bdrc_scan_id: W1GS54156
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T06:43:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T02:23:19.154430+00:00'
last_modified: 2022-08-27 10:23:56.578019
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS54156
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1GS54156
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལེགས་བཤད་དཔེ་ཚོགས་ནོར་བུའི་ཕྲེང་བ། （༡）
statistics:
  ocr_word_mean_confidence_index: 0.7630997616938724
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG13745:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13745
      total_pages: 600
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13745.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7630997616938724
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
