id: I1980B469
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:47:35+00:00'
last_modified: '2022-06-08T13:08:08.959488+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS54156
  title: ལེགས་བཤད་དཔེ་ཚོགས་ནོར་བུའི་ཕྲེང་བ། （༡）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    70C3:
      image_group_id: I1KG13745
      title: Volume 1 of legs bshad dpe tshogs nor bu'i phreng ba :1
      total_pages: 600
      order: 1
      base_file: 70C3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
